apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.externalSecretName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secrets.externalSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: DEVAI_OPENAI_API_KEY
      remoteRef:
        key: devai-openai-api-key
    - secretKey: DEVAI_ANTHROPIC_API_KEY
      remoteRef:
        key: devai-anthropic-api-key
    - secretKey: DEVAI_GITHUB_APP_PRIVATE_KEY
      remoteRef:
        key: devai-github-app-private-key
    - secretKey: DEVAI_GITHUB_WEBHOOK_SECRET
      remoteRef:
        key: devai-github-webhook-secret
    - secretKey: DEVAI_GITHUB_APP_ID
      remoteRef:
        key: devai-github-app-id
    - secretKey: DEVAI_GITHUB_APP_INSTALLATION_ID
      remoteRef:
        key: devai-github-app-installation-id
