apiVersion: registry.solo.io/v1alpha1
kind: Skill
metadata:
  name: google-google-cloud-waf-performance-optimization
  namespace: devai
  labels:
    devai.io/source: community
    devai.io/origin: voltagent-awesome-skills
    devai.io/category: ai
    devai.io/team: google
    devai.io/risk-level: low
spec:
  displayName: Google Cloud Waf Performance Optimization
  description: Generates performance-focused guidance for Google Cloud workloads based on the design principles
    and recommendations in the Performance Optimization pillar of the Google Cloud Well...
  category: ai
  version: '1'
  tags:
  - ai
  - github
  - google
  - voltagent-awesome-skills
  metadata:
    owner: google
    origin: voltagent-awesome-skills
    source: github
    upstream_id: google/cloud/google-cloud-waf-performance-optimization
