apiVersion: registry.solo.io/v1alpha1
kind: Skill
metadata:
  name: google-gemini-interactions-api
  namespace: devai
  labels:
    devai.io/source: community
    devai.io/origin: voltagent-awesome-skills
    devai.io/category: ai
    devai.io/team: google
    devai.io/risk-level: low
spec:
  displayName: Gemini Interactions Api
  description: Guides the usage of Gemini Interactions API on Gemini Enterprise Agent Platform.
  category: ai
  version: '1'
  tags:
  - ai
  - github
  - google
  - voltagent-awesome-skills
  metadata:
    owner: google
    origin: voltagent-awesome-skills
    source: github
    upstream_id: google/cloud/gemini-interactions-api
