apiVersion: registry.solo.io/v1alpha1
kind: Skill
metadata:
  name: microsoft-azure-storage-file-share-py
  namespace: devai
  labels:
    devai.io/source: community
    devai.io/origin: voltagent-awesome-skills
    devai.io/category: coding
    devai.io/team: microsoft
    devai.io/risk-level: low
spec:
  displayName: Azure Storage File Share Py
  description: SMB file share management
  category: coding
  version: '1'
  tags:
  - coding
  - microsoft
  - officialskills.sh
  - voltagent-awesome-skills
  metadata:
    owner: microsoft
    origin: voltagent-awesome-skills
    source: officialskills.sh
    upstream_id: microsoft/azure-storage-file-share-py
